# Generated by Django 2.2.7 on 2019-11-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_slide_captionstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='captionStyle',
            field=models.CharField(choices=[('caption left-align', 'Baslık Solda'), ('caption right-align', 'Baslık Sagda'), ('caption center-align', 'Baslık Ortada')], default='caption left-align', max_length=25),
        ),
    ]
