# Generated by Django 2.2.7 on 2019-12-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191126_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('slideImage', models.ImageField(upload_to='card_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
